### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by akshayreddykotha** [chinmayeeb96/Analytics_Vidhya_Dataverse_Hackathon#1]
Hi, 

I was reading through your approach and tried to replicate it. One question I had was all the feature engineering you did sounds good but does that not leverage the power of catboost using categorical indices? Because once all the feature engineering is done, there is not even one feature as category dtype as everything is either dummy encoded or 1/0 or oridnal. And the performance after feature engineering was slightly lower than when the model leveraged categorical indices.

Any thoughts?

Thanks and Congrats!

**Comment by chinmayeeb96** [comment]
While using the CatBoost we have not use feature engineering. Those feature engineering were used initially.
